--QUERY FOR PULLING COLUMN NAMES AND ASSOCIATED DATA TYPE FOR A GIVEN TABLE--
SELECT 
    TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'SCHEMA_NAME' AND
    TABLE_NAME = 'TABLE_NAME' AND
    COLUMN_NAME IN ('column1', 'column2', 'column3')
    