/** 
CREATES A COPY OF TABLE BASED ON AN EXISTING TABLE
COPIES ALL DATA AND TABLE SCHEMA BUT DOES NOT COPY INDICIES OR CONSTRAINTS
**/

SELECT *
INTO [schema_name].[table_name_backup]
FROM [schema_name].[table_name]
